services:
  qlink_local:
    image: postgres:16
    container_name: qlink_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: qlink
    ports:
      - "5432:5432"
