services:
  qlink_local:
    image: postgres:18
    container_name: qlink_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: qlink
    ports:
      - "5432:5432"
