ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.qlink.ApplicationKt.module

dataSource:
  jdbcUrl: ${DB_JDBC_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driverClassName: ${DB_DRIVER_CLASS_NAME}

flyway:
  schema: qlink_local
  locations:
    - db/migration
    - db/data

http:
  cors:
    methods:
      - OPTIONS
      - HEAD
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Requested-With
      - MyCustomHeader
    allowCredentials: true
    allowNonSimpleContentTypes: true
    anyHost: true
    hosts:
      - localhost:8081
  defaultHeaders:
    engine:
      name: X-Engine
      value: Ktor
  documentation:
    openApiPath: openapi
    swaggerPath: docs
    redocPath: redoc

monitoring:
  metricsPath: /metrics-micrometer

logging:
  http:
    slowThresholdMs: 1000
    maxLength: 4096
    traceIdLength: 12
    sensitiveKeys:
      - accessToken
      - refreshToken

security:
  jwt:
    secret: Y1d4cGJtc3RZbTl2YTIxaGNtdHo=
