aws_region = "ap-northeast-2"

vpc_cidr = "172.31.0.0/16"
az_a     = "ap-northeast-2a"
az_c     = "ap-northeast-2c"

public_subnet_a_cidr  = "172.31.0.0/20"
public_subnet_c_cidr  = "172.31.32.0/20"
private_subnet_a_cidr = "172.31.128.0/20"
private_subnet_c_cidr = "172.31.144.0/20"

vpc_name                 = "qlink-default"
igw_name                 = "qlink-igw"
public_subnet_a_name     = "qlink-default-public-a"
public_subnet_c_name     = "qlink-default-public-c"
private_subnet_a_name    = "qlink-private-a"
private_subnet_c_name    = "qlink-private-c"
public_route_table_name  = "qlink-public"
private_route_table_name = "qlink-private-rtb-a"
s3_endpoint_name         = "qlink-s3-endpoint"

alb_sg_name               = "qlinkAlbGroup"
alb_sg_description        = "ALB Security Group"
app_sg_name               = "qlinkAppGroup"
app_sg_description        = "ECS Security Group"
rds_app_sg_name           = "qlinkRdsAppGroup"
rds_app_sg_description    = "RDS App Security Group"
rds_public_sg_name        = "qlinkRdsPublicGroup"
rds_public_sg_description = "RDS Public Security Group"
rds_public_ingress_cidrs  = ["0.0.0.0/0"]

alb_name                  = "qlink-alb-dev"
alb_tag_name              = "qlink-alb-dev"
target_group_name         = "qlink-tg-dev"
target_group_tag_name     = "qlink-tg-dev"
listener_tag_name         = "qlink-alb-listener"
https_listener_tag_name   = "qlink-alb-https-listener"
acm_certificate_arn       = "arn:aws:acm:ap-northeast-2:650177546654:certificate/aa14e1b6-aef4-4f74-bea6-2bff4afc8508"
https_listener_ssl_policy = "ELBSecurityPolicy-TLS13-1-2-Res-PQ-2025-09"
route53_hosted_zone_id    = "Z0975649ZPWG98ONPYZP"

ecr_image_tag_mutability = "IMMUTABLE"
ecr_image_scan_on_push   = false
ecr_max_image_count      = 20

ecs_key_pair_name               = "qlink-dev-ssh"
ecs_instance_role_name          = "ecsInstanceRole"
ecs_instance_role_policy_arn    = "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
ecs_instance_profile_name       = "ecsInstanceRole"
ecs_cluster_name                = "qlink-ecs-cluster-dev"
ecs_cluster_tag_name            = "qlink-ecs-cluster-dev"
launch_template_name            = "ECSLaunchTemplate_jHFSMI7rg3iG"
launch_template_image_id        = "ami-08767fd97a1f677c7"
launch_template_instance_type   = "t4g.small"
ecs_instance_tag_name           = "ECS Instance - qlink-ecs-cluster-dev"
asg_name                        = "Infra-ECS-Cluster-qlink-ecs-cluster-dev-83711ad6-ECSAutoScalingGroup-BC1LQMGTj6KX"
asg_min_size                    = 0
asg_max_size                    = 2
asg_desired_capacity            = 1
capacity_provider_name          = "Infra-ECS-Cluster-qlink-ecs-cluster-dev-83711ad6-AsgCapacityProvider-XECa6njigrke"
additional_capacity_providers   = ["FARGATE", "FARGATE_SPOT"]
task_execution_role_name        = "ecsTaskExecutionRole"
task_execution_role_policy_arn  = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
ecs_log_group_name              = "/ecs/qlink-ecs-task-dev"
ecs_log_group_retention_in_days = 7
ecs_task_family                 = "qlink-ecs-task-dev"
ecs_task_cpu                    = "1024"
ecs_task_memory                 = "1792"
ecs_task_container_name         = "qlink-app-dev"
ecs_task_container_port         = 8080
ecs_task_port_name              = "ktor-webapp-port"
ecs_task_app_protocol           = "http"
ecs_task_healthcheck_command    = "wget -qO- http://localhost:8080/health >/dev/null || exit 1"
ecs_task_definition_tag_name    = "qlink-ecs-task-dev"
ecs_service_name                = "qlink-ecs-service-dev"
ecs_service_desired_count       = 1
ecs_service_tag_name            = "qlink-ecs-service-dev"

db_subnet_group_name                = "qlink-db-subnet-group-public"
db_subnet_group_tag_name            = "qlink DB subnet group public"
rds_identifier                      = "qlink-rds-dev-pg18"
rds_engine                          = "postgres"
rds_engine_version                  = "18"
rds_instance_class                  = "db.t4g.micro"
rds_allocated_storage               = 20
rds_storage_type                    = "gp3"
rds_iops                            = null
rds_storage_throughput              = null
rds_availability_zone               = "ap-northeast-2a"
rds_publicly_accessible             = true
rds_multi_az                        = false
rds_enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]
rds_skip_final_snapshot             = true
rds_instance_tag_name               = "qlink-rds-dev-pg18"
