name: 개발 서버 배포 자동화

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: read

jobs:
  detect:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ steps.filter.outputs.infra }}
      infra_shared_changed: ${{ steps.filter.outputs.infra_shared }}
      app_changed: ${{ steps.filter.outputs.app }}
    steps:
      - name: 체크아웃
        uses: actions/checkout@v6

      - name: 변경사항 감지
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infra:
              - 'terraform/dev/**'
              - 'terraform/modules/**'
            infra_shared:
              - 'terraform/shared/**'
            app:
              - 'src/**'
              - 'build.gradle.kts'
              - 'settings.gradle.kts'
              - 'gradle/**'
              - 'Dockerfile'
              - '.github/workflows/**'
              - '.gitmodules'
              - 'secrets/**'

  infra_update:
    needs: detect
    if: ${{ needs.detect.outputs.infra_changed == 'true' }}
    uses: ./.github/workflows/infra-pipeline.yml
    with:
      env: dev
      ecr_repository_name: qlink-ecr-dev
      ecr_repository_tag_name: qlink-ecr-dev
      rds_db_name: qlink
      rds_username: qlink
      infra_update_enabled: ${{ needs.detect.outputs.infra_changed == 'true' }}
      infra_shared_update_enabled: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      SUBMODULES_SECRET: ${{ secrets.SUBMODULES_SECRET }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}

  dev_deploy:
    needs:
      - detect
      - infra_update
    if: ${{ always() && needs.detect.result == 'success' && (needs.detect.outputs.app_changed == 'true' || needs.detect.outputs.infra_changed == 'true') && (needs.infra_update.result == 'success' || needs.infra_update.result == 'skipped') }}
    uses: ./.github/workflows/deploy-pipeline.yml
    with:
      env: dev
      deployment_enabled: true
      ecr_repository_name: qlink-ecr-dev
      ecr_repository_tag_name: qlink-ecr-dev
      rds_db_name: qlink
      rds_username: qlink
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      SUBMODULES_SECRET: ${{ secrets.SUBMODULES_SECRET }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
