name: 개발 서버 인프라 수동 배포

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  infra_update:
    uses: ./.github/workflows/infra-pipeline.yml
    with:
      env: dev
      ecr_repository_name: qlink-ecr-dev
      ecr_repository_tag_name: qlink-ecr-dev
      rds_db_name: qlink
      rds_username: qlink
      infra_update_enabled: true
      infra_shared_update_enabled: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      SUBMODULES_SECRET: ${{ secrets.SUBMODULES_SECRET }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      TF_VAR_FCM_SERVICE_ACCOUNT_JSON: ${{ secrets.DEV_FCM_SERVICE_ACCOUNT_JSON }}
      TF_VAR_EXPO_ACCESS_TOKEN: ${{ secrets.DEV_EXPO_ACCESS_TOKEN }}
